# Generated by Django 5.2 on 2025-05-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ngo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('user', 'User'), ('ngo', 'NGO')], default='user', max_length=10),
        ),
    ]
