# Generated by Django 5.2 on 2025-05-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
