# Generated by Django 5.2 on 2025-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ngo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
