# Generated by Django 5.2 on 2025-05-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ngo_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
