# Generated by Django 5.2 on 2025-05-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_ngo_phone_number_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('card', 'Credit Card')], default='cash', max_length=20),
        ),
    ]
